site_name: AgenaTrader Tutorials
docs_dir: sources
theme: readthedocs
site_favicon: favicon.ico
extra_css: [custom.css]
use_directory_urls: true
repo_url: https://github.com/AgenaTrader/Tutorials
edit_uri: edit/master/sources/
site_url: https://agenatrader.github.io/Tutorials/
strict: true
google_analytics: ['UA-74646070-1', 'agenatrader.github.io']
pages:
    - 'Lets start': 'index.md'
    - 'Basic Example': 'Example_Indicator_Condition_Strategy_Basic/README.md'
    - 'Advanced Example': 'Example_Indicator_Condition_Strategy_Advanced/README.md'
