site_name: AgenaTrader Tutorials
docs_dir: sources
theme: readthedocs
pages:
    - 'Home': 'index.md'
    - 'Basic Template': 'Example_Indicator_Condition_Strategy_Basic/README.md'
    - 'Advanced Template': 'Example_Indicator_Condition_Strategy_Advanced/README.md'